"""Database creation

Revision ID: c0729150fb76
Revises: 
Create Date: 2024-08-10 10:28:44.081743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0729150fb76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('note', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('region', sa.String(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('create_on', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('parent_user_id', sa.Integer(), nullable=True),
                    sa.Column('notes_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('notes')
    # ### end Alembic commands ###
