"""Adding notifications

Revision ID: e12520765b38
Revises: 5205a6589cf2
Create Date: 2024-12-16 21:37:03.919946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e12520765b38'
down_revision: Union[str, None] = '5205a6589cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification', sa.String(), nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('create_on', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('clients_notes_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'notes_id')
    op.drop_column('clients', 'parent_user_id')
    op.add_column('notes', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notes', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'client_id')
    op.add_column('clients', sa.Column('parent_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('notes_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('clients_notes_id_fkey', 'clients', 'notes', ['notes_id'], ['id'])
    op.drop_table('notifications')
    # ### end Alembic commands ###
